'use client';

import React, { useState, useEffect } from 'react';
import {
    Download, FileSpreadsheet, FileText, FileJson,
    Check, Filter, Calendar, Package, Ticket, Users,
    FileQuestion, UserCheck, Wrench, CreditCard, ChevronRight
} from 'lucide-react';

// Entity icons mapping
const ICON_MAP = {
    Ticket: Ticket,
    Users: Users,
    FileQuestion: FileQuestion,
    Package: Package,
    UserCheck: UserCheck,
    Wrench: Wrench,
    CreditCard: CreditCard
};

// Default export entities configuration
const DEFAULT_ENTITIES = [
    { key: 'tickets', label: 'Service Tickets', icon: 'Ticket', description: 'All service requests and tickets' },
    { key: 'customers', label: 'Customers', icon: 'Users', description: 'Registered customer accounts' },
    { key: 'invoices', label: 'Invoices', icon: 'CreditCard', description: 'Generated invoices and payments' },
    { key: 'products', label: 'Products', icon: 'Package', description: 'Product catalog' },
    { key: 'quoteRequests', label: 'Quote Requests', icon: 'FileQuestion', description: 'Product quote requests' },
    { key: 'agents', label: 'Agents/Admins', icon: 'UserCheck', description: 'System agents and administrators' },
    { key: 'services', label: 'Services', icon: 'Wrench', description: 'Available service types' }
];

// Field configurations per entity
const ENTITY_FIELDS = {
    tickets: [
        { key: 'id', label: 'ID' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'serviceType', label: 'Service Type' },
        { key: 'product', label: 'Product' },
        { key: 'priority', label: 'Priority' },
        { key: 'status', label: 'Status' },
        { key: 'subject', label: 'Subject' },
        { key: 'description', label: 'Description' },
        { key: 'assignedTo', label: 'Assigned To' },
        { key: 'comments', label: 'Comments' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    customers: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'verified', label: 'Verified' },
        { key: 'createdAt', label: 'Created At' }
    ],
    invoices: [
        { key: 'id', label: 'ID' },
        { key: 'invoiceNumber', label: 'Invoice Number' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'amount', label: 'Amount' },
        { key: 'status', label: 'Status' },
        { key: 'generatedBy', label: 'Generated By' },
        { key: 'items', label: 'Items' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    products: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'price', label: 'Price' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ],
    quoteRequests: [
        { key: 'id', label: 'ID' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'guestEmail', label: 'Guest Email' },
        { key: 'guestPhone', label: 'Guest Phone' },
        { key: 'productName', label: 'Product' },
        { key: 'message', label: 'Message' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    agents: [
        { key: 'id', label: 'ID' },
        { key: 'username', label: 'Username' },
        { key: 'email', label: 'Email' },
        { key: 'role', label: 'Role' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    services: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ]
};

// Filter configurations per entity
const ENTITY_FILTERS = {
    tickets: [
        { key: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Completed', 'Cancelled'] },
        { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
        { key: 'serviceType', label: 'Service Type', type: 'text' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    customers: [
        { key: 'verified', label: 'Verified', type: 'select', options: [{ value: 'true', label: 'Verified' }, { value: 'false', label: 'Not Verified' }] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    invoices: [
        { key: 'status', label: 'Status', type: 'select', options: ['Paid', 'Unpaid', 'Pending', 'Cancelled'] },
        { key: 'minAmount', label: 'Min Amount', type: 'number' },
        { key: 'maxAmount', label: 'Max Amount', type: 'number' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    products: [
        { key: 'minPrice', label: 'Min Price', type: 'number' },
        { key: 'maxPrice', label: 'Max Price', type: 'number' }
    ],
    quoteRequests: [
        { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Reviewed', 'Sent'] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    agents: [
        { key: 'role', label: 'Role', type: 'select', options: ['admin', 'agent', 'superadmin'] },
        { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'suspended'] }
    ],
    services: []
};

const DATE_PRESETS = [
    { value: '', label: 'All Time' },
    { value: 'today', label: 'Today' },
    { value: 'yesterday', label: 'Yesterday' },
    { value: 'last7days', label: 'Last 7 Days' },
    { value: 'last30days', label: 'Last 30 Days' },
    { value: 'thisMonth', label: 'This Month' },
    { value: 'lastMonth', label: 'Last Month' },
    { value: 'thisYear', label: 'This Year' }
];

const EXPORT_FORMATS = [
    { key: 'xlsx', label: 'Excel (.xlsx)', icon: FileSpreadsheet, description: 'Best for large datasets' },
    { key: 'csv', label: 'CSV (.csv)', icon: FileText, description: 'Universal format' },
    { key: 'json', label: 'JSON (.json)', icon: FileJson, description: 'Developer friendly' }
];

export default function ExportDataClient() {
    const [selectedEntity, setSelectedEntity] = useState(null);
    const [selectedFields, setSelectedFields] = useState([]);
    const [filters, setFilters] = useState({});
    const [format, setFormat] = useState('xlsx');
    const [isExporting, setIsExporting] = useState(false);
    const [exportProgress, setExportProgress] = useState(0);
    const [showFilters, setShowFilters] = useState(true);
    const [showFields, setShowFields] = useState(true);

    // Initialize fields when entity changes
    useEffect(() => {
        if (selectedEntity && ENTITY_FIELDS[selectedEntity]) {
            setSelectedFields(ENTITY_FIELDS[selectedEntity].map(f => f.key));
        }
    }, [selectedEntity]);

    const handleFieldToggle = (fieldKey) => {
        setSelectedFields(prev =>
            prev.includes(fieldKey)
                ? prev.filter(f => f !== fieldKey)
                : [...prev, fieldKey]
        );
    };

    const handleSelectAllFields = () => {
        if (selectedEntity && ENTITY_FIELDS[selectedEntity]) {
            setSelectedFields(ENTITY_FIELDS[selectedEntity].map(f => f.key));
        }
    };

    const handleDeselectAllFields = () => {
        setSelectedFields([]);
    };

    const handleFilterChange = (key, value) => {
        setFilters(prev => ({ ...prev, [key]: value }));
    };

    const handleExport = async () => {
        if (!selectedEntity || selectedFields.length === 0) return;

        setIsExporting(true);
        setExportProgress(10);

        try {
            const exportData = {
                entity: selectedEntity,
                fields: selectedFields,
                filters: filters,
                format: format
            };

            setExportProgress(30);

            const response = await fetch('/api/admin/export', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(exportData)
            });

            setExportProgress(70);

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error || 'Export failed');
            }

            const contentDisposition = response.headers.get('Content-Disposition');
            const filenameMatch = contentDisposition?.match(/filename="(.+)"/);
            const defaultFilename = `${selectedEntity}_export_${new Date().toISOString().slice(0, 10)}`;
            const filename = filenameMatch ? filenameMatch[1] : defaultFilename;

            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);

            setExportProgress(100);

            setTimeout(() => {
                setIsExporting(false);
                setExportProgress(0);
            }, 1500);

        } catch (error) {
            console.error('Export error:', error);
            alert(`Export failed: ${error.message}`);
            setIsExporting(false);
            setExportProgress(0);
        }
    };

    const getIconComponent = (iconName) => {
        const Icon = ICON_MAP[iconName] || Package;
        return Icon;
    };

    const canExport = selectedEntity && selectedFields.length > 0;

    return (
        <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
            {/* Header */}
            <div>
                <h1 className="title-lg mb-2" style={{ margin: 0, fontWeight: 900 }}>Data <span className="gradient-text">Export</span></h1>
                <p className="text-dim mt-4" style={{ fontSize: '0.875rem' }}>Select data to export in your preferred format.</p>
            </div>

            {/* Main Content */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>

                {/* Left Column - Entity Selection */}
                <div className="glass" style={{ padding: '1.5rem' }}>
                    <h3 style={{ fontWeight: 'bold', marginBottom: '1.5rem', marginTop: 0 }}>Select Data Type</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                        {DEFAULT_ENTITIES.map((entity) => {
                            const Icon = getIconComponent(entity.icon);
                            return (
                                <button
                                    key={entity.key}
                                    onClick={() => {
                                        setSelectedEntity(entity.key);
                                        setFilters({});
                                    }}
                                    style={{
                                        display: 'flex',
                                        alignItems: 'center',
                                        gap: '0.75rem',
                                        padding: '1rem',
                                        borderRadius: '0.75rem',
                                        border: `2px solid ${selectedEntity === entity.key ? 'var(--primary)' : 'var(--border-glass)'}`,
                                        background: selectedEntity === entity.key ? 'rgba(108, 99, 255, 0.1)' : 'transparent',
                                        cursor: 'pointer',
                                        transition: 'all 0.2s ease',
                                        textAlign: 'left'
                                    }}
                                >
                                    <div style={{
                                        width: '2.5rem',
                                        height: '2.5rem',
                                        borderRadius: '0.5rem',
                                        background: selectedEntity === entity.key ? 'var(--primary)' : 'rgba(255,255,255,0.05)',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center',
                                        color: selectedEntity === entity.key ? '#fff' : 'var(--text-dim)'
                                    }}>
                                        <Icon size={20} />
                                    </div>
                                    <div>
                                        <div style={{ fontWeight: 600, color: '#fff', fontSize: '0.875rem' }}>{entity.label}</div>
                                        <div style={{ fontSize: '0.65rem', color: 'var(--text-dim)' }}>{entity.description}</div>
                                    </div>
                                </button>
                            );
                        })}
                    </div>
                </div>

                {/* Right Column - Options */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>

                    {/* Field Selection */}
                    {selectedEntity && (
                        <div className="glass" style={{ padding: '1.5rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                                <h3 style={{ fontWeight: 'bold', margin: 0 }}>Select Fields</h3>
                                <div style={{ display: 'flex', gap: '0.5rem' }}>
                                    <button
                                        onClick={handleSelectAllFields}
                                        style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem', background: 'rgba(255,255,255,0.05)', border: 'none', borderRadius: '0.25rem', color: 'var(--text-dim)', cursor: 'pointer' }}
                                    >
                                        All
                                    </button>
                                    <button
                                        onClick={handleDeselectAllFields}
                                        style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem', background: 'rgba(255,255,255,0.05)', border: 'none', borderRadius: '0.25rem', color: 'var(--text-dim)', cursor: 'pointer' }}
                                    >
                                        None
                                    </button>
                                </div>
                            </div>

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', maxHeight: '200px', overflowY: 'auto' }}>
                                {ENTITY_FIELDS[selectedEntity]?.map((field) => (
                                    <label
                                        key={field.key}
                                        style={{
                                            display: 'flex',
                                            alignItems: 'center',
                                            gap: '0.5rem',
                                            padding: '0.5rem',
                                            borderRadius: '0.375rem',
                                            cursor: 'pointer',
                                            background: selectedFields.includes(field.key) ? 'rgba(108, 99, 255, 0.1)' : 'transparent',
                                            border: `1px solid ${selectedFields.includes(field.key) ? 'var(--primary)' : 'transparent'}`
                                        }}
                                    >
                                        <input
                                            type="checkbox"
                                            checked={selectedFields.includes(field.key)}
                                            onChange={() => handleFieldToggle(field.key)}
                                            style={{ accentColor: 'var(--primary)' }}
                                        />
                                        <span style={{ fontSize: '0.8rem', color: selectedFields.includes(field.key) ? '#fff' : 'var(--text-dim)' }}>
                                            {field.label}
                                        </span>
                                    </label>
                                ))}
                            </div>
                            <p style={{ fontSize: '0.75rem', color: 'var(--text-dim)', marginTop: '0.75rem', marginBottom: 0 }}>
                                {selectedFields.length} of {ENTITY_FIELDS[selectedEntity]?.length || 0} fields selected
                            </p>
                        </div>
                    )}

                    {/* Filters */}
                    {selectedEntity && ENTITY_FILTERS[selectedEntity]?.length > 0 && (
                        <div className="glass" style={{ padding: '1.5rem' }}>
                            <button
                                onClick={() => setShowFilters(!showFilters)}
                                style={{
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '0.5rem',
                                    background: 'none',
                                    border: 'none',
                                    cursor: 'pointer',
                                    width: '100%',
                                    marginBottom: showFilters ? '1rem' : 0
                                }}
                            >
                                <Filter size={18} style={{ color: 'var(--primary)' }} />
                                <h3 style={{ fontWeight: 'bold', margin: 0, flex: 1, textAlign: 'left' }}>Filters</h3>
                                <ChevronRight
                                    size={18}
                                    style={{
                                        color: 'var(--text-dim)',
                                        transform: showFilters ? 'rotate(90deg)' : 'rotate(0deg)',
                                        transition: 'transform 0.2s'
                                    }}
                                />
                            </button>

                            {showFilters && (
                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
                                    {ENTITY_FILTERS[selectedEntity].map((filter) => (
                                        <div key={filter.key}>
                                            <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-dim)', marginBottom: '0.25rem' }}>
                                                {filter.label}
                                            </label>
                                            {filter.type === 'select' && (
                                                <select
                                                    value={filters[filter.key] || ''}
                                                    onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                    style={{
                                                        width: '100%',
                                                        padding: '0.5rem',
                                                        background: 'rgba(255,255,255,0.05)',
                                                        border: '1px solid var(--border-glass)',
                                                        borderRadius: '0.375rem',
                                                        color: '#fff',
                                                        fontSize: '0.8rem'
                                                    }}
                                                >
                                                    <option value="">All</option>
                                                    {filter.options.map((opt) => (
                                                        <option key={opt.value || opt} value={opt.value || opt}>
                                                            {opt.label || opt}
                                                        </option>
                                                    ))}
                                                </select>
                                            )}
                                            {filter.type === 'text' && (
                                                <input
                                                    type="text"
                                                    value={filters[filter.key] || ''}
                                                    onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                    placeholder="Enter value..."
                                                    style={{
                                                        width: '100%',
                                                        padding: '0.5rem',
                                                        background: 'rgba(255,255,255,0.05)',
                                                        border: '1px solid var(--border-glass)',
                                                        borderRadius: '0.375rem',
                                                        color: '#fff',
                                                        fontSize: '0.8rem'
                                                    }}
                                                />
                                            )}
                                            {filter.type === 'number' && (
                                                <input
                                                    type="number"
                                                    value={filters[filter.key] || ''}
                                                    onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                    placeholder="Enter value..."
                                                    style={{
                                                        width: '100%',
                                                        padding: '0.5rem',
                                                        background: 'rgba(255,255,255,0.05)',
                                                        border: '1px solid var(--border-glass)',
                                                        borderRadius: '0.375rem',
                                                        color: '#fff',
                                                        fontSize: '0.8rem'
                                                    }}
                                                />
                                            )}
                                            {filter.type === 'datePreset' && (
                                                <select
                                                    value={filters.datePreset || ''}
                                                    onChange={(e) => handleFilterChange('datePreset', e.target.value)}
                                                    style={{
                                                        width: '100%',
                                                        padding: '0.5rem',
                                                        background: 'rgba(255,255,255,0.05)',
                                                        border: '1px solid var(--border-glass)',
                                                        borderRadius: '0.375rem',
                                                        color: '#fff',
                                                        fontSize: '0.8rem'
                                                    }}
                                                >
                                                    {DATE_PRESETS.map((preset) => (
                                                        <option key={preset.value} value={preset.value}>
                                                            {preset.label}
                                                        </option>
                                                    ))}
                                                </select>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}

                    {/* Format Selection */}
                    <div className="glass" style={{ padding: '1.5rem' }}>
                        <h3 style={{ fontWeight: 'bold', marginBottom: '1rem', marginTop: 0 }}>Export Format</h3>
                        <div style={{ display: 'flex', gap: '0.75rem' }}>
                            {EXPORT_FORMATS.map((fmt) => {
                                const Icon = fmt.icon;
                                return (
                                    <button
                                        key={fmt.key}
                                        onClick={() => setFormat(fmt.key)}
                                        style={{
                                            flex: 1,
                                            display: 'flex',
                                            flexDirection: 'column',
                                            alignItems: 'center',
                                            gap: '0.5rem',
                                            padding: '1rem',
                                            borderRadius: '0.75rem',
                                            border: `2px solid ${format === fmt.key ? 'var(--primary)' : 'var(--border-glass)'}`,
                                            background: format === fmt.key ? 'rgba(108, 99, 255, 0.1)' : 'transparent',
                                            cursor: 'pointer',
                                            transition: 'all 0.2s'
                                        }}
                                    >
                                        <Icon size={24} style={{ color: format === fmt.key ? 'var(--primary)' : 'var(--text-dim)' }} />
                                        <span style={{ fontSize: '0.75rem', fontWeight: 600, color: format === fmt.key ? '#fff' : 'var(--text-dim)' }}>
                                            {fmt.key.toUpperCase()}
                                        </span>
                                    </button>
                                );
                            })}
                        </div>
                    </div>

                    {/* Export Button */}
                    <button
                        onClick={handleExport}
                        disabled={!canExport || isExporting}
                        style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: '0.75rem',
                            padding: '1rem 2rem',
                            borderRadius: '0.75rem',
                            border: 'none',
                            background: canExport && !isExporting
                                ? 'linear-gradient(135deg, var(--primary), #0082C8)'
                                : 'rgba(255,255,255,0.05)',
                            color: canExport && !isExporting ? '#fff' : 'var(--text-dim)',
                            fontWeight: 600,
                            fontSize: '1rem',
                            cursor: canExport && !isExporting ? 'pointer' : 'not-allowed',
                            boxShadow: canExport && !isExporting ? '0 4px 20px rgba(108, 99, 255, 0.3)' : 'none',
                            transition: 'all 0.2s'
                        }}
                    >
                        {isExporting ? (
                            <>Processing... {exportProgress}%</>
                        ) : (
                            <>
                                <Download size={20} />
                                Export Data
                            </>
                        )}
                    </button>

                    {/* Progress Bar */}
                    {isExporting && (
                        <div style={{
                            width: '100%',
                            height: '4px',
                            background: 'rgba(255,255,255,0.1)',
                            borderRadius: '2px',
                            overflow: 'hidden'
                        }}>
                            <div style={{
                                width: `${exportProgress}%`,
                                height: '100%',
                                background: 'var(--primary)',
                                transition: 'width 0.3s'
                            }} />
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
