'use client';

import { useState, useEffect } from 'react';
import {
    X, Download, FileSpreadsheet, FileText, FileJson,
    ChevronRight, ChevronDown, Check, Filter, Calendar,
    Package, Ticket, Users, FileQuestion, UserCheck, Wrench
} from 'lucide-react';

// Entity icons mapping
const ICON_MAP = {
    Ticket: Ticket,
    Users: Users,
    FileText: FileQuestion,
    Package: Package,
    FileQuestion: FileQuestion,
    UserCheck: UserCheck,
    Wrench: Wrench
};

// Default export entities configuration
const DEFAULT_ENTITIES = [
    { key: 'tickets', label: 'Service Tickets', icon: 'Ticket', description: 'All service requests and tickets' },
    { key: 'customers', label: 'Customers', icon: 'Users', description: 'Registered customer accounts' },
    { key: 'invoices', label: 'Invoices', icon: 'FileText', description: 'Generated invoices and payments' },
    { key: 'products', label: 'Products', icon: 'Package', description: 'Product catalog' },
    { key: 'quoteRequests', label: 'Quote Requests', icon: 'FileQuestion', description: 'Product quote requests' },
    { key: 'agents', label: 'Agents/Admins', icon: 'UserCheck', description: 'System agents and administrators' },
    { key: 'services', label: 'Services', icon: 'Wrench', description: 'Available service types' }
];

// Field configurations per entity
const ENTITY_FIELDS = {
    tickets: [
        { key: 'id', label: 'ID' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'serviceType', label: 'Service Type' },
        { key: 'product', label: 'Product' },
        { key: 'priority', label: 'Priority' },
        { key: 'status', label: 'Status' },
        { key: 'subject', label: 'Subject' },
        { key: 'description', label: 'Description' },
        { key: 'assignedTo', label: 'Assigned To' },
        { key: 'comments', label: 'Comments' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    customers: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'verified', label: 'Verified' },
        { key: 'createdAt', label: 'Created At' }
    ],
    invoices: [
        { key: 'id', label: 'ID' },
        { key: 'invoiceNumber', label: 'Invoice Number' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'amount', label: 'Amount' },
        { key: 'status', label: 'Status' },
        { key: 'generatedBy', label: 'Generated By' },
        { key: 'items', label: 'Items' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    products: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'price', label: 'Price' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ],
    quoteRequests: [
        { key: 'id', label: 'ID' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'guestEmail', label: 'Guest Email' },
        { key: 'guestPhone', label: 'Guest Phone' },
        { key: 'productName', label: 'Product' },
        { key: 'message', label: 'Message' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    agents: [
        { key: 'id', label: 'ID' },
        { key: 'username', label: 'Username' },
        { key: 'email', label: 'Email' },
        { key: 'role', label: 'Role' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    services: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ]
};

// Filter configurations per entity
const ENTITY_FILTERS = {
    tickets: [
        { key: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Completed', 'Cancelled'] },
        { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
        { key: 'serviceType', label: 'Service Type', type: 'text' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    customers: [
        { key: 'verified', label: 'Verified', type: 'select', options: [{ value: 'true', label: 'Verified' }, { value: 'false', label: 'Not Verified' }] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    invoices: [
        { key: 'status', label: 'Status', type: 'select', options: ['Paid', 'Unpaid', 'Pending', 'Cancelled'] },
        { key: 'minAmount', label: 'Min Amount', type: 'number' },
        { key: 'maxAmount', label: 'Max Amount', type: 'number' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    products: [
        { key: 'minPrice', label: 'Min Price', type: 'number' },
        { key: 'maxPrice', label: 'Max Price', type: 'number' }
    ],
    quoteRequests: [
        { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Reviewed', 'Sent'] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    agents: [
        { key: 'role', label: 'Role', type: 'select', options: ['admin', 'agent', 'superadmin'] },
        { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'suspended'] }
    ],
    services: []
};

const DATE_PRESETS = [
    { value: '', label: 'All Time' },
    { value: 'today', label: 'Today' },
    { value: 'yesterday', label: 'Yesterday' },
    { value: 'last7days', label: 'Last 7 Days' },
    { value: 'last30days', label: 'Last 30 Days' },
    { value: 'thisMonth', label: 'This Month' },
    { value: 'lastMonth', label: 'Last Month' },
    { value: 'thisYear', label: 'This Year' }
];

const EXPORT_FORMATS = [
    { key: 'xlsx', label: 'Excel (.xlsx)', icon: FileSpreadsheet, description: 'Best for large datasets' },
    { key: 'csv', label: 'CSV (.csv)', icon: FileText, description: 'Universal format' },
    { key: 'json', label: 'JSON (.json)', icon: FileJson, description: 'Developer friendly' }
];

export default function ExportModal({ isOpen, onClose }) {
    const [step, setStep] = useState(1);
    const [selectedEntity, setSelectedEntity] = useState(null);
    const [selectedFields, setSelectedFields] = useState([]);
    const [expandedFields, setExpandedFields] = useState({});
    const [filters, setFilters] = useState({});
    const [format, setFormat] = useState('xlsx');
    const [isExporting, setIsExporting] = useState(false);
    const [exportProgress, setExportProgress] = useState(0);
    const [showAdvancedFilters, setShowAdvancedFilters] = useState(false);

    // Reset state when modal opens
    useEffect(() => {
        if (isOpen) {
            setStep(1);
            setSelectedEntity(null);
            setSelectedFields([]);
            setExpandedFields({});
            setFilters({});
            setFormat('xlsx');
            setIsExporting(false);
            setExportProgress(0);
            setShowAdvancedFilters(false);
        }
    }, [isOpen]);

    // Initialize fields when entity changes
    useEffect(() => {
        if (selectedEntity && ENTITY_FIELDS[selectedEntity]) {
            setSelectedFields(ENTITY_FIELDS[selectedEntity].map(f => f.key));
        }
    }, [selectedEntity]);

    const handleFieldToggle = (fieldKey) => {
        setSelectedFields(prev =>
            prev.includes(fieldKey)
                ? prev.filter(f => f !== fieldKey)
                : [...prev, fieldKey]
        );
    };

    const handleSelectAllFields = () => {
        if (selectedEntity && ENTITY_FIELDS[selectedEntity]) {
            setSelectedFields(ENTITY_FIELDS[selectedEntity].map(f => f.key));
        }
    };

    const handleDeselectAllFields = () => {
        setSelectedFields([]);
    };

    const handleFilterChange = (key, value) => {
        setFilters(prev => ({ ...prev, [key]: value }));
    };

    const handleExport = async () => {
        setIsExporting(true);
        setExportProgress(10);

        try {
            // Prepare export data
            const exportData = {
                entity: selectedEntity,
                fields: selectedFields,
                filters: filters,
                format: format
            };

            setExportProgress(30);

            // Make API call
            const response = await fetch('/api/admin/export', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(exportData)
            });

            setExportProgress(70);

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error || 'Export failed');
            }

            // Get filename from headers
            const contentDisposition = response.headers.get('Content-Disposition');
            const filenameMatch = contentDisposition?.match(/filename="(.+)"/);
            const defaultFilename = `${selectedEntity}_export_${new Date().toISOString().slice(0, 10)}`;
            const filename = filenameMatch ? filenameMatch[1] : defaultFilename;

            // Convert to blob and download
            const blob = await response.blob();
            const url = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(url);
            document.body.removeChild(a);

            setExportProgress(100);

            // Close modal after short delay
            setTimeout(() => {
                onClose();
            }, 1000);

        } catch (error) {
            console.error('Export error:', error);
            alert(`Export failed: ${error.message}`);
            setIsExporting(false);
            setExportProgress(0);
        }
    };

    const getIconComponent = (iconName) => {
        const Icon = ICON_MAP[iconName] || Package;
        return Icon;
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                onClick={onClose}
            />

            {/* Modal */}
            <div className="relative w-full max-w-4xl max-h-[90vh] bg-[#0a0a0f] border border-[#2a2a3a] rounded-2xl shadow-2xl overflow-hidden flex flex-col">
                {/* Header */}
                <div className="flex items-center justify-between px-8 py-6 border-b border-[#2a2a3a] bg-gradient-to-r from-[#1a1a2e] to-[#0a0a0f]">
                    <div>
                        <h2 className="text-2xl font-bold text-white">Export Data</h2>
                        <p className="text-sm text-gray-400 mt-1">
                            {step === 1 && 'Select data to export'}
                            {step === 2 && 'Choose fields to include'}
                            {step === 3 && 'Configure filters and export'}
                        </p>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-[#2a2a3a] rounded-lg transition-colors"
                    >
                        <X className="w-5 h-5 text-gray-400" />
                    </button>
                </div>

                {/* Progress Steps */}
                <div className="flex items-center justify-center gap-2 py-4 border-b border-[#2a2a3a] bg-[#0f0f1a]">
                    {[1, 2, 3].map((s) => (
                        <div key={s} className="flex items-center">
                            <div className={`
                w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold
                ${step >= s
                                    ? 'bg-[#6C63FF] text-white'
                                    : 'bg-[#2a2a3a] text-gray-500'}
              `}>
                                {step > s ? <Check className="w-4 h-4" /> : s}
                            </div>
                            {s < 3 && (
                                <div className={`w-16 h-0.5 mx-2 ${step > s ? 'bg-[#6C63FF]' : 'bg-[#2a2a3a]'}`} />
                            )}
                        </div>
                    ))}
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-8">
                    {/* Step 1: Entity Selection */}
                    {step === 1 && (
                        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                            {DEFAULT_ENTITIES.map((entity) => {
                                const Icon = getIconComponent(entity.icon);
                                return (
                                    <button
                                        key={entity.key}
                                        onClick={() => {
                                            setSelectedEntity(entity.key);
                                            setFilters({});
                                        }}
                                        className={`
                      p-6 rounded-xl border-2 text-left transition-all duration-200
                      ${selectedEntity === entity.key
                                                ? 'border-[#6C63FF] bg-[#6C63FF]/10 shadow-lg shadow-[#6C63FF]/20'
                                                : 'border-[#2a2a3a] hover:border-[#4a4a5a] hover:bg-[#1a1a2e]'
                                            }
                    `}
                                    >
                                        <div className={`w-12 h-12 rounded-lg flex items-center justify-center mb-4 ${selectedEntity === entity.key
                                                ? 'bg-[#6C63FF]/20 text-[#6C63FF]'
                                                : 'bg-[#2a2a3a] text-gray-400'
                                            }`}>
                                            <Icon className="w-6 h-6" />
                                        </div>
                                        <h3 className="font-semibold text-white mb-1">{entity.label}</h3>
                                        <p className="text-xs text-gray-500">{entity.description}</p>
                                    </button>
                                );
                            })}
                        </div>
                    )}

                    {/* Step 2: Field Selection */}
                    {step === 2 && selectedEntity && (
                        <div>
                            <div className="flex items-center justify-between mb-6">
                                <h3 className="text-lg font-semibold text-white">
                                    Select Fields for {DEFAULT_ENTITIES.find(e => e.key === selectedEntity)?.label}
                                </h3>
                                <div className="flex gap-2">
                                    <button
                                        onClick={handleSelectAllFields}
                                        className="px-3 py-1.5 text-sm bg-[#2a2a3a] hover:bg-[#3a3a4a] text-gray-300 rounded-lg transition-colors"
                                    >
                                        Select All
                                    </button>
                                    <button
                                        onClick={handleDeselectAllFields}
                                        className="px-3 py-1.5 text-sm bg-[#2a2a3a] hover:bg-[#3a3a4a] text-gray-300 rounded-lg transition-colors"
                                    >
                                        Deselect All
                                    </button>
                                </div>
                            </div>

                            <div className="grid grid-cols-2 md:grid-cols-3 gap-3 max-h-[400px] overflow-y-auto pr-2">
                                {ENTITY_FIELDS[selectedEntity]?.map((field) => (
                                    <label
                                        key={field.key}
                                        className={`
                      flex items-center gap-3 p-3 rounded-lg border cursor-pointer transition-all
                      ${selectedFields.includes(field.key)
                                                ? 'border-[#6C63FF] bg-[#6C63FF]/10'
                                                : 'border-[#2a2a3a] hover:border-[#4a4a5a]'
                                            }
                    `}
                                    >
                                        <div className={`
                      w-5 h-5 rounded border-2 flex items-center justify-center transition-colors
                      ${selectedFields.includes(field.key)
                                                ? 'bg-[#6C63FF] border-[#6C63FF]'
                                                : 'border-gray-500'
                                            }
                    `}>
                                            {selectedFields.includes(field.key) && (
                                                <Check className="w-3 h-3 text-white" />
                                            )}
                                        </div>
                                        <input
                                            type="checkbox"
                                            checked={selectedFields.includes(field.key)}
                                            onChange={() => handleFieldToggle(field.key)}
                                            className="hidden"
                                        />
                                        <span className="text-sm text-gray-200">{field.label}</span>
                                    </label>
                                ))}
                            </div>

                            <p className="text-sm text-gray-500 mt-4">
                                {selectedFields.length} of {ENTITY_FIELDS[selectedEntity]?.length || 0} fields selected
                            </p>
                        </div>
                    )}

                    {/* Step 3: Filters and Export */}
                    {step === 3 && selectedEntity && (
                        <div>
                            {/* Filters Section */}
                            <div className="mb-8">
                                <button
                                    onClick={() => setShowAdvancedFilters(!showAdvancedFilters)}
                                    className="flex items-center gap-2 text-white font-medium mb-4"
                                >
                                    <Filter className="w-5 h-5" />
                                    Advanced Filters
                                    {showAdvancedFilters ? (
                                        <ChevronDown className="w-4 h-4" />
                                    ) : (
                                        <ChevronRight className="w-4 h-4" />
                                    )}
                                </button>

                                {showAdvancedFilters && (
                                    <div className="grid grid-cols-2 gap-4 p-6 bg-[#1a1a2e] rounded-xl border border-[#2a2a3a]">
                                        {ENTITY_FILTERS[selectedEntity]?.map((filter) => (
                                            <div key={filter.key}>
                                                <label className="block text-sm text-gray-400 mb-2">{filter.label}</label>
                                                {filter.type === 'select' && (
                                                    <select
                                                        value={filters[filter.key] || ''}
                                                        onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                        className="w-full px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                    >
                                                        <option value="">All</option>
                                                        {filter.options.map((opt) => (
                                                            <option key={opt.value || opt} value={opt.value || opt}>
                                                                {opt.label || opt}
                                                            </option>
                                                        ))}
                                                    </select>
                                                )}
                                                {filter.type === 'text' && (
                                                    <input
                                                        type="text"
                                                        value={filters[filter.key] || ''}
                                                        onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                        placeholder="Enter value..."
                                                        className="w-full px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                    />
                                                )}
                                                {filter.type === 'number' && (
                                                    <input
                                                        type="number"
                                                        value={filters[filter.key] || ''}
                                                        onChange={(e) => handleFilterChange(filter.key, e.target.value)}
                                                        placeholder="Enter value..."
                                                        className="w-full px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                    />
                                                )}
                                                {filter.type === 'datePreset' && (
                                                    <div className="flex gap-2">
                                                        <select
                                                            value={filters.datePreset || ''}
                                                            onChange={(e) => handleFilterChange('datePreset', e.target.value)}
                                                            className="flex-1 px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                        >
                                                            {DATE_PRESETS.map((preset) => (
                                                                <option key={preset.value} value={preset.value}>
                                                                    {preset.label}
                                                                </option>
                                                            ))}
                                                        </select>
                                                        {filters.datePreset === 'custom' && (
                                                            <>
                                                                <input
                                                                    type="date"
                                                                    value={filters.dateFrom || ''}
                                                                    onChange={(e) => handleFilterChange('dateFrom', e.target.value)}
                                                                    className="flex-1 px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                                />
                                                                <input
                                                                    type="date"
                                                                    value={filters.dateTo || ''}
                                                                    onChange={(e) => handleFilterChange('dateTo', e.target.value)}
                                                                    className="flex-1 px-4 py-2.5 bg-[#0a0a0f] border border-[#2a2a3a] rounded-lg text-white text-sm focus:border-[#6C63FF] focus:outline-none"
                                                                />
                                                            </>
                                                        )}
                                                    </div>
                                                )}
                                            </div>
                                        ))}
                                        {(!ENTITY_FILTERS[selectedEntity] || ENTITY_FILTERS[selectedEntity].length === 0) && (
                                            <p className="text-sm text-gray-500 col-span-2">
                                                No filters available for this entity
                                            </p>
                                        )}
                                    </div>
                                )}
                            </div>

                            {/* Format Selection */}
                            <div>
                                <h3 className="text-lg font-semibold text-white mb-4">Export Format</h3>
                                <div className="grid grid-cols-3 gap-4">
                                    {EXPORT_FORMATS.map((fmt) => {
                                        const Icon = fmt.icon;
                                        return (
                                            <button
                                                key={fmt.key}
                                                onClick={() => setFormat(fmt.key)}
                                                className={`
                          p-4 rounded-xl border-2 text-left transition-all
                          ${format === fmt.key
                                                        ? 'border-[#6C63FF] bg-[#6C63FF]/10'
                                                        : 'border-[#2a2a3a] hover:border-[#4a4a5a]'
                                                    }
                        `}
                                            >
                                                <Icon className={`w-8 h-8 mb-3 ${format === fmt.key ? 'text-[#6C63FF]' : 'text-gray-400'}`} />
                                                <h4 className="font-medium text-white">{fmt.label}</h4>
                                                <p className="text-xs text-gray-500 mt-1">{fmt.description}</p>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Export Summary */}
                            <div className="mt-8 p-6 bg-[#1a1a2e] rounded-xl border border-[#2a2a3a]">
                                <h4 className="font-semibold text-white mb-4">Export Summary</h4>
                                <div className="grid grid-cols-2 gap-4 text-sm">
                                    <div>
                                        <span className="text-gray-500">Entity:</span>
                                        <span className="text-white ml-2">
                                            {DEFAULT_ENTITIES.find(e => e.key === selectedEntity)?.label}
                                        </span>
                                    </div>
                                    <div>
                                        <span className="text-gray-500">Fields:</span>
                                        <span className="text-white ml-2">{selectedFields.length} selected</span>
                                    </div>
                                    <div>
                                        <span className="text-gray-500">Format:</span>
                                        <span className="text-white ml-2 uppercase">{format}</span>
                                    </div>
                                    <div>
                                        <span className="text-gray-500">Active Filters:</span>
                                        <span className="text-white ml-2">
                                            {Object.values(filters).filter(v => v).length} applied
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {/* Export Progress */}
                            {isExporting && (
                                <div className="mt-6 p-4 bg-[#1a1a2e] rounded-xl border border-[#6C63FF]">
                                    <div className="flex items-center justify-between mb-2">
                                        <span className="text-sm text-white">Exporting data...</span>
                                        <span className="text-sm text-[#6C63FF]">{exportProgress}%</span>
                                    </div>
                                    <div className="w-full h-2 bg-[#2a2a3a] rounded-full overflow-hidden">
                                        <div
                                            className="h-full bg-[#6C63FF] transition-all duration-300"
                                            style={{ width: `${exportProgress}%` }}
                                        />
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="flex items-center justify-between px-8 py-6 border-t border-[#2a2a3a] bg-[#0a0a0f]">
                    <button
                        onClick={() => step > 1 ? setStep(step - 1) : onClose()}
                        className="px-6 py-2.5 text-gray-400 hover:text-white transition-colors"
                    >
                        {step > 1 ? 'Back' : 'Cancel'}
                    </button>

                    {step < 3 ? (
                        <button
                            onClick={() => setStep(step + 1)}
                            disabled={step === 1 && !selectedEntity}
                            className={`
                px-6 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all
                ${step === 1 && !selectedEntity
                                    ? 'bg-[#2a2a3a] text-gray-500 cursor-not-allowed'
                                    : 'bg-[#6C63FF] hover:bg-[#5a52e0] text-white'
                                }
              `}
                        >
                            Continue
                            <ChevronRight className="w-4 h-4" />
                        </button>
                    ) : (
                        <button
                            onClick={handleExport}
                            disabled={isExporting || selectedFields.length === 0}
                            className={`
                px-8 py-2.5 rounded-lg font-medium flex items-center gap-2 transition-all
                ${isExporting || selectedFields.length === 0
                                    ? 'bg-[#2a2a3a] text-gray-500 cursor-not-allowed'
                                    : 'bg-gradient-to-r from-[#6C63FF] to-[#8b7cff] hover:from-[#5a52e0] hover:to-[#7a6ce0] text-white shadow-lg shadow-[#6C63FF]/30'
                                }
              `}
                        >
                            {isExporting ? (
                                <>Processing...</>
                            ) : (
                                <>
                                    <Download className="w-4 h-4" />
                                    Export Data
                                </>
                            )}
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
}
