/**
 * Export Constants
 * Centralized configuration for export functionality
 * This eliminates code duplication between ExportModal and ExportDataClient
 */

// Entity icons mapping
export const ICON_MAP = {
    Ticket: 'Ticket',
    Users: 'Users',
    FileText: 'FileText',
    Package: 'Package',
    FileQuestion: 'FileQuestion',
    UserCheck: 'UserCheck',
    Wrench: 'Wrench',
    CreditCard: 'CreditCard'
};

// Default export entities configuration
export const DEFAULT_ENTITIES = [
    { key: 'tickets', label: 'Service Tickets', icon: 'Ticket', description: 'All service requests and tickets' },
    { key: 'customers', label: 'Customers', icon: 'Users', description: 'Registered customer accounts' },
    { key: 'invoices', label: 'Invoices', icon: 'CreditCard', description: 'Generated invoices and payments' },
    { key: 'products', label: 'Products', icon: 'Package', description: 'Product catalog' },
    { key: 'quoteRequests', label: 'Quote Requests', icon: 'FileQuestion', description: 'Product quote requests' },
    { key: 'agents', label: 'Agents/Admins', icon: 'UserCheck', description: 'System agents and administrators' },
    { key: 'services', label: 'Services', icon: 'Wrench', description: 'Available service types' }
];

// Field configurations per entity
export const ENTITY_FIELDS = {
    tickets: [
        { key: 'id', label: 'ID' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'serviceType', label: 'Service Type' },
        { key: 'product', label: 'Product' },
        { key: 'priority', label: 'Priority' },
        { key: 'status', label: 'Status' },
        { key: 'subject', label: 'Subject' },
        { key: 'description', label: 'Description' },
        { key: 'assignedTo', label: 'Assigned To' },
        { key: 'comments', label: 'Comments' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    customers: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'email', label: 'Email' },
        { key: 'phone', label: 'Phone' },
        { key: 'verified', label: 'Verified' },
        { key: 'createdAt', label: 'Created At' }
    ],
    invoices: [
        { key: 'id', label: 'ID' },
        { key: 'invoiceNumber', label: 'Invoice Number' },
        { key: 'ticketNumber', label: 'Ticket Number' },
        { key: 'amount', label: 'Amount' },
        { key: 'status', label: 'Status' },
        { key: 'generatedBy', label: 'Generated By' },
        { key: 'items', label: 'Items' },
        { key: 'createdAt', label: 'Created At' },
        { key: 'updatedAt', label: 'Updated At' }
    ],
    products: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'price', label: 'Price' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ],
    quoteRequests: [
        { key: 'id', label: 'ID' },
        { key: 'customerName', label: 'Customer Name' },
        { key: 'guestEmail', label: 'Guest Email' },
        { key: 'guestPhone', label: 'Guest Phone' },
        { key: 'productName', label: 'Product' },
        { key: 'message', label: 'Message' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    agents: [
        { key: 'id', label: 'ID' },
        { key: 'username', label: 'Username' },
        { key: 'email', label: 'Email' },
        { key: 'role', label: 'Role' },
        { key: 'status', label: 'Status' },
        { key: 'createdAt', label: 'Created At' }
    ],
    services: [
        { key: 'id', label: 'ID' },
        { key: 'name', label: 'Name' },
        { key: 'description', label: 'Description' },
        { key: 'image', label: 'Image URL' },
        { key: 'createdAt', label: 'Created At' }
    ]
};

// Filter configurations per entity
export const ENTITY_FILTERS = {
    tickets: [
        { key: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Completed', 'Cancelled'] },
        { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
        { key: 'serviceType', label: 'Service Type', type: 'text' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    customers: [
        { key: 'verified', label: 'Verified', type: 'select', options: [{ value: 'true', label: 'Verified' }, { value: 'false', label: 'Not Verified' }] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    invoices: [
        { key: 'status', label: 'Status', type: 'select', options: ['Paid', 'Unpaid', 'Pending', 'Cancelled'] },
        { key: 'minAmount', label: 'Min Amount', type: 'number' },
        { key: 'maxAmount', label: 'Max Amount', type: 'number' },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    products: [
        { key: 'minPrice', label: 'Min Price', type: 'number' },
        { key: 'maxPrice', label: 'Max Price', type: 'number' }
    ],
    quoteRequests: [
        { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Reviewed', 'Sent'] },
        { key: 'datePreset', label: 'Date Range', type: 'datePreset' }
    ],
    agents: [
        { key: 'role', label: 'Role', type: 'select', options: ['admin', 'agent', 'superadmin'] },
        { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'suspended'] }
    ],
    services: []
};

// Date range presets
export const DATE_PRESETS = [
    { value: '', label: 'All Time' },
    { value: 'today', label: 'Today' },
    { value: 'yesterday', label: 'Yesterday' },
    { value: 'last7days', label: 'Last 7 Days' },
    { value: 'last30days', label: 'Last 30 Days' },
    { value: 'thisMonth', label: 'This Month' },
    { value: 'lastMonth', label: 'Last Month' },
    { value: 'thisYear', label: 'This Year' }
];

// Export format options
export const EXPORT_FORMATS = [
    { key: 'xlsx', label: 'Excel (.xlsx)', description: 'Best for large datasets' },
    { key: 'csv', label: 'CSV (.csv)', description: 'Universal format' },
    { key: 'json', label: 'JSON (.json)', description: 'Developer friendly' }
];

// Pagination defaults
export const EXPORT_PAGINATION = {
    DEFAULT_PAGE_SIZE: 1000,
    MAX_PAGE_SIZE: 10000
};
