/**
 * Data Export Configuration
 * Production-grade export system with advanced filtering and field selection
 */

import * as XLSX from 'xlsx';

// Exportable entities configuration
export const EXPORT_ENTITIES = {
    tickets: {
        label: 'Service Tickets',
        model: 'ticket',
        description: 'All service requests and tickets',
        icon: 'Ticket',
        defaultFields: [
            'ticketNumber', 'customerName', 'email', 'phone', 'serviceType',
            'product', 'priority', 'status', 'subject', 'description',
            'assignedTo', 'createdAt', 'updatedAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'ticketNumber', label: 'Ticket Number', type: 'string' },
            { key: 'customerName', label: 'Customer Name', type: 'string' },
            { key: 'email', label: 'Email', type: 'string' },
            { key: 'phone', label: 'Phone', type: 'string' },
            { key: 'serviceType', label: 'Service Type', type: 'string' },
            { key: 'product', label: 'Product', type: 'string' },
            { key: 'priority', label: 'Priority', type: 'string' },
            { key: 'status', label: 'Status', type: 'string' },
            { key: 'subject', label: 'Subject', type: 'string' },
            { key: 'description', label: 'Description', type: 'string' },
            { key: 'assignedTo', label: 'Assigned To', type: 'string' },
            { key: 'comments', label: 'Comments', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
            { key: 'updatedAt', label: 'Updated At', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Completed', 'Cancelled'] },
            { key: 'priority', label: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
            { key: 'serviceType', label: 'Service Type', type: 'text' },
            { key: 'dateFrom', label: 'Date From', type: 'date' },
            { key: 'dateTo', label: 'Date To', type: 'date' },
        ]
    },
    customers: {
        label: 'Customers',
        model: 'customer',
        description: 'Registered customer accounts',
        icon: 'Users',
        defaultFields: [
            'id', 'name', 'email', 'phone', 'verified', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'name', label: 'Name', type: 'string' },
            { key: 'email', label: 'Email', type: 'string' },
            { key: 'phone', label: 'Phone', type: 'string' },
            { key: 'verified', label: 'Verified', type: 'boolean' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
        ],
        filters: [
            { key: 'verified', label: 'Verified', type: 'select', options: ['true', 'false'] },
            { key: 'dateFrom', label: 'Date From', type: 'date' },
            { key: 'dateTo', label: 'Date To', type: 'date' },
        ]
    },
    invoices: {
        label: 'Invoices',
        model: 'invoice',
        description: 'Generated invoices and payments',
        icon: 'FileText',
        defaultFields: [
            'invoiceNumber', 'ticketNumber', 'amount', 'status', 'generatedBy', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'invoiceNumber', label: 'Invoice Number', type: 'string' },
            { key: 'ticketNumber', label: 'Ticket Number', type: 'string' },
            { key: 'amount', label: 'Amount', type: 'number' },
            { key: 'status', label: 'Status', type: 'string' },
            { key: 'generatedBy', label: 'Generated By', type: 'string' },
            { key: 'items', label: 'Items', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
            { key: 'updatedAt', label: 'Updated At', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', type: 'select', options: ['Paid', 'Unpaid', 'Pending', 'Cancelled'] },
            { key: 'dateFrom', label: 'Date From', type: 'date' },
            { key: 'dateTo', label: 'Date To', type: 'date' },
            { key: 'minAmount', label: 'Min Amount', type: 'number' },
            { key: 'maxAmount', label: 'Max Amount', type: 'number' },
        ]
    },
    products: {
        label: 'Products',
        model: 'product',
        description: 'Product catalog',
        icon: 'Package',
        defaultFields: [
            'id', 'name', 'description', 'price', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'name', label: 'Name', type: 'string' },
            { key: 'description', label: 'Description', type: 'string' },
            { key: 'price', label: 'Price', type: 'number' },
            { key: 'image', label: 'Image URL', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
        ],
        filters: [
            { key: 'minPrice', label: 'Min Price', type: 'number' },
            { key: 'maxPrice', label: 'Max Price', type: 'number' },
        ]
    },
    quoteRequests: {
        label: 'Quote Requests',
        model: 'quoteRequest',
        description: 'Product quote requests',
        icon: 'FileQuestion',
        defaultFields: [
            'id', 'customerName', 'guestEmail', 'productName', 'message', 'status', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'customerName', label: 'Customer Name', type: 'string' },
            { key: 'customerEmail', label: 'Customer Email', type: 'string' },
            { key: 'customerPhone', label: 'Customer Phone', type: 'string' },
            { key: 'productName', label: 'Product', type: 'string' },
            { key: 'message', label: 'Message', type: 'string' },
            { key: 'status', label: 'Status', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
        ],
        filters: [
            { key: 'status', label: 'Status', type: 'select', options: ['Pending', 'Reviewed', 'Sent'] },
            { key: 'dateFrom', label: 'Date From', type: 'date' },
            { key: 'dateTo', label: 'Date To', type: 'date' },
        ]
    },
    agents: {
        label: 'Agents/Admins',
        model: 'admin',
        description: 'System agents and administrators',
        icon: 'UserCheck',
        defaultFields: [
            'id', 'username', 'email', 'role', 'status', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'username', label: 'Username', type: 'string' },
            { key: 'email', label: 'Email', type: 'string' },
            { key: 'role', label: 'Role', type: 'string' },
            { key: 'status', label: 'Status', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
        ],
        filters: [
            { key: 'role', label: 'Role', type: 'select', options: ['admin', 'agent', 'superadmin'] },
            { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'suspended'] },
        ]
    },
    services: {
        label: 'Services',
        model: 'service',
        description: 'Available service types',
        icon: 'Wrench',
        defaultFields: [
            'id', 'name', 'description', 'createdAt'
        ],
        availableFields: [
            { key: 'id', label: 'ID', type: 'number' },
            { key: 'name', label: 'Name', type: 'string' },
            { key: 'description', label: 'Description', type: 'string' },
            { key: 'image', label: 'Image URL', type: 'string' },
            { key: 'createdAt', label: 'Created At', type: 'date' },
        ],
        filters: []
    }
};

// Export format options
export const EXPORT_FORMATS = {
    xlsx: {
        label: 'Excel (.xlsx)',
        extension: '.xlsx',
        mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    },
    csv: {
        label: 'CSV (.csv)',
        extension: '.csv',
        mimeType: 'text/csv'
    },
    json: {
        label: 'JSON (.json)',
        extension: '.json',
        mimeType: 'application/json'
    }
};

// Date range presets
export const DATE_PRESETS = [
    { label: 'Today', value: 'today' },
    { label: 'Yesterday', value: 'yesterday' },
    { label: 'Last 7 Days', value: 'last7days' },
    { label: 'Last 30 Days', value: 'last30days' },
    { label: 'This Month', value: 'thisMonth' },
    { label: 'Last Month', value: 'lastMonth' },
    { label: 'This Year', value: 'thisYear' },
    { label: 'Custom Range', value: 'custom' }
];

/**
 * Build Prisma query filters based on export configuration
 */
export function buildPrismaFilters(entity, filters) {
    const where = {};

    switch (entity) {
        case 'tickets':
            if (filters.status) where.status = filters.status;
            if (filters.priority) where.priority = filters.priority;
            if (filters.serviceType) where.serviceType = { contains: filters.serviceType, mode: 'insensitive' };
            if (filters.dateFrom || filters.dateTo) {
                where.createdAt = {};
                if (filters.dateFrom) where.createdAt.gte = new Date(filters.dateFrom);
                if (filters.dateTo) where.createdAt.lte = new Date(filters.dateTo);
            }
            break;

        case 'customers':
            if (filters.verified !== undefined) where.verified = filters.verified === 'true';
            if (filters.dateFrom || filters.dateTo) {
                where.createdAt = {};
                if (filters.dateFrom) where.createdAt.gte = new Date(filters.dateFrom);
                if (filters.dateTo) where.createdAt.lte = new Date(filters.dateTo);
            }
            break;

        case 'invoices':
            if (filters.status) where.status = filters.status;
            if (filters.dateFrom || filters.dateTo) {
                where.createdAt = {};
                if (filters.dateFrom) where.createdAt.gte = new Date(filters.dateFrom);
                if (filters.dateTo) where.createdAt.lte = new Date(filters.dateTo);
            }
            if (filters.minAmount || filters.maxAmount) {
                where.amount = {};
                if (filters.minAmount) where.amount.gte = parseFloat(filters.minAmount);
                if (filters.maxAmount) where.amount.lte = parseFloat(filters.maxAmount);
            }
            break;

        case 'products':
            if (filters.minPrice || filters.maxPrice) {
                where.price = {};
                if (filters.minPrice) where.price.gte = parseFloat(filters.minPrice);
                if (filters.maxPrice) where.price.lte = parseFloat(filters.maxPrice);
            }
            break;

        case 'quoteRequests':
            if (filters.status) where.status = filters.status;
            if (filters.dateFrom || filters.dateTo) {
                where.createdAt = {};
                if (filters.dateFrom) where.createdAt.gte = new Date(filters.dateFrom);
                if (filters.dateTo) where.createdAt.lte = new Date(filters.dateTo);
            }
            break;

        case 'agents':
            if (filters.role) where.role = filters.role;
            if (filters.status) where.status = filters.status;
            break;
    }

    return where;
}

/**
 * Transform data for export based on selected fields
 */
export function transformDataForExport(data, entity, selectedFields) {
    const config = EXPORT_ENTITIES[entity];
    if (!config) return data;

    return data.map(item => {
        const transformed = {};
        selectedFields.forEach(field => {
            let value = item[field];

            // Handle nested relations
            if (field === 'assignedTo' && item.assignedTo) {
                value = item.assignedTo.username;
            }
            if (field === 'ticketNumber' && item.ticket) {
                value = item.ticket.ticketNumber;
            }
            if (field === 'productName' && item.product) {
                value = item.product.name;
            }
            if (field === 'customerName' && item.customer) {
                value = item.customer.name;
            }
            if (field === 'customerEmail' && item.customer) {
                value = item.customer.email;
            }
            if (field === 'customerPhone' && item.customer) {
                value = item.customer.phone;
            }

            // Format dates
            if (value instanceof Date) {
                value = value.toISOString();
            }

            // Format booleans
            if (typeof value === 'boolean') {
                value = value ? 'Yes' : 'No';
            }

            // Handle Decimal types
            if (value && typeof value === 'object' && value.toNumber) {
                value = parseFloat(value.toNumber());
            }

            transformed[field] = value ?? '';
        });
        return transformed;
    });
}

/**
 * Export data to XLSX format
 */
export function exportToXLSX(data, filename, sheetName = 'Data') {
    const worksheet = XLSX.utils.json_to_sheet(data);

    // Set column widths
    const maxWidths = {};
    data.forEach(row => {
        Object.keys(row).forEach(key => {
            const value = String(row[key] || '');
            maxWidths[key] = Math.max(maxWidths[key] || 0, value.length, key.length);
        });
    });

    worksheet['!cols'] = Object.keys(maxWidths).map(key => ({
        wch: Math.min(maxWidths[key] + 2, 50)
    }));

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);

    // Generate buffer
    const buffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'buffer' });

    return buffer;
}

/**
 * Export data to CSV format
 */
export function exportToCSV(data) {
    if (data.length === 0) return '';

    const headers = Object.keys(data[0]);
    const csvRows = [];

    // Header row
    csvRows.push(headers.map(h => `"${h}"`).join(','));

    // Data rows
    data.forEach(row => {
        const values = headers.map(header => {
            const value = row[header];
            if (value === null || value === undefined) return '';
            const stringValue = String(value);
            // Escape quotes and wrap in quotes if contains comma or quote
            if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
                return `"${stringValue.replace(/"/g, '""')}"`;
            }
            return stringValue;
        });
        csvRows.push(values.join(','));
    });

    return csvRows.join('\n');
}

/**
 * Generate export filename
 */
export function generateExportFilename(entity, format) {
    const timestamp = new Date().toISOString().slice(0, 10);
    const entityLabel = entity.toLowerCase().replace(/s$/, ''); // Remove trailing 's'
    return `${entityLabel}_export_${timestamp}`;
}

/**
 * Apply date preset to get date range
 */
export function applyDatePreset(preset) {
    const now = new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

    switch (preset) {
        case 'today':
            return { dateFrom: today.toISOString(), dateTo: now.toISOString() };
        case 'yesterday':
            const yesterday = new Date(today);
            yesterday.setDate(yesterday.getDate() - 1);
            return { dateFrom: yesterday.toISOString(), dateTo: today.toISOString() };
        case 'last7days':
            const last7 = new Date(today);
            last7.setDate(last7.getDate() - 7);
            return { dateFrom: last7.toISOString(), dateTo: now.toISOString() };
        case 'last30days':
            const last30 = new Date(today);
            last30.setDate(last30.getDate() - 30);
            return { dateFrom: last30.toISOString(), dateTo: now.toISOString() };
        case 'thisMonth':
            const thisMonthStart = new Date(now.getFullYear(), now.getMonth(), 1);
            return { dateFrom: thisMonthStart.toISOString(), dateTo: now.toISOString() };
        case 'lastMonth':
            const lastMonthStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
            const lastMonthEnd = new Date(now.getFullYear(), now.getMonth(), 0);
            return { dateFrom: lastMonthStart.toISOString(), dateTo: lastMonthEnd.toISOString() };
        case 'thisYear':
            const thisYearStart = new Date(now.getFullYear(), 0, 1);
            return { dateFrom: thisYearStart.toISOString(), dateTo: now.toISOString() };
        default:
            return {};
    }
}
