-- AlterTable
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "category" TEXT DEFAULT 'General';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "display_order" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "featured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "is_active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updated_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
